### ISSUE TITLE
What is the use of prism themes?

### ISSUE THREAD

**Issue by AusPrinzip** [nuxt-academy/demo-blog-nuxt-content#74]
Given that you can choose from a list of themes directly from nuxt config file, first use that comes to mind is global style theming.
````
    markdown: {
      prism: {
        theme: 'prism-themes/themes/prism-hopscotch.css'
      }
    },
````

However, this themes have apparently no impact whatsoever on the blog style.

Further looking at the original repository, "prism" seems to be a theme repository for text editors.

Can someone clarify the purpose of this asset in nuxt blog demo?

**Comment by atinux** [comment]
@AusPrinzip Prism is used for code block highlighting, the theme can be configured from Nuxt Content, see https://content.nuxtjs.org/configuration#markdownprismtheme
